import { ethers } from "ethers";

/**
 * Connects to a local Hardhat node, verifies its status, checks for a deployed contract,
 * and displays the balance of a common test account. Provides troubleshooting steps
 * if the node is not running or the contract is not deployed.
 */
async function checkHardhatNode() {
  try {
    console.log("🔍 Checking Hardhat node status...");

    // Hardhat's default RPC URL for local development.
    const provider = new ethers.JsonRpcProvider("http://127.0.0.1:8545");

    // Attempt to retrieve network information to confirm node connectivity.
    const network = await provider.getNetwork();
    console.log("✅ Hardhat node is running!");
    console.log("📍 Network:", {
      name: network.name,
      chainId: network.chainId.toString(), // Convert BigInt to string for display.
    });

    // Hardcoded contract address from Hardhat's default deployment for the first contract.
    const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
    const code = await provider.getCode(contractAddress);

    if (code === "0x") {
      console.log("❌ Contract not deployed at", contractAddress);
      console.log(
        "💡 Run: npx hardhat ignition deploy ignition/modules/AgriYield.ts --network localhost"
      );
    } else {
      console.log("✅ Contract deployed at", contractAddress);
    }

    // Hardcoded test account (first account generated by Hardhat local node).
    const testAccount = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
    const balance = await provider.getBalance(testAccount);
    console.log("💰 Test account balance:", ethers.formatEther(balance), "ETH");

    console.log(
      "\n🎉 Everything looks good! Ready for blockchain transactions."
    );
  } catch (error: any) {
    console.error("❌ Hardhat node check failed:", error.message);
    console.log("\n💡 To fix this:");
    console.log("1. Start Hardhat node: npx hardhat node");
    console.log(
      "2. Deploy contract: npx hardhat ignition deploy ignition/modules/AgriYield.ts --network localhost"
    );
    console.log(
      "3. Add Hardhat Local network to MetaMask (Chain ID: 31337, RPC: http://127.0.0.1:8545)"
    );
    console.log(
      "4. Import test account private key (first account): 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    );
  }
}

checkHardhatNode();
